image:
  - Visual Studio 2015
  - Visual Studio 2017
build: off
test_script:
  - ps: .\ver.ps1
  - ps: if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq 'Visual Studio 2017') { docker run -v "${pwd}:C:\mnt" microsoft/nanoserver@sha256:8f78a4a7da4464973a5cd239732626141aec97e69ba3e4023357628630bc1ee2 powershell.exe -f C:\mnt\ver.ps1 }
  - ps: if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq 'Visual Studio 2017') { docker run -v "${pwd}:C:\mnt" microsoft/windowsservercore@sha256:c06b4bfaf634215ea194e6005450740f3a230b27c510cf8facab1e9c678f3a99 powershell.exe -f C:\mnt\ver.ps1 }
