pool:
  vmImage: windows-2019
steps:
  - checkout: self
    clean: true
    lfs: false
    fetchDepth: 1
    submodules: false
  - powershell: gp 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion'
    displayName: Print operating system infos
  - powershell: 'ls env:'
    displayName: Print environment variables
  - powershell: $env:path -split ';' | % { ls $_\*.exe | % { $_.fullname } } | sort
    displayName: Print available binaries
  - powershell: gci 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\VisualStudio' -r
    displayName: List VS registry
  - powershell: ls "C:\Program Files (x86)\Microsoft Visual Studio" -r -de 10 -file | where { $_.name -like "*.exe" } | % { $_.fullname } | sort
    displayName: List VS binaries
