jobs:
  - job: Windows
    pool:
      vmImage: windows-2019
    steps:
      - powershell: .\ver.ps1
  - job: Windows
    pool:
      vmImage: win1803
    steps:
      - powershell: .\ver.ps1
  - job: Windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - powershell: .\ver.ps1
  - job: Windows
    pool:
      vmImage: vs2015-win2012r2
    steps:
      - powershell: .\ver.ps1
