pool:
  vmImage: vs2017-win2016
steps:
  - checkout: self
    clean: true
    lfs: false
    fetchDepth: 1
    submodules: false
  - powershell: gp 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion'
    displayName: Print operating system infos
  - powershell: 'ls env:'
    displayName: Print environment variables
  - powershell: $env:path -split ';' | % { ls $_\*.exe | % { $_.fullname } } | sort
    displayName: Print available binaries
