name: CI
on: push
defaults:
  run:
    shell: cmd
jobs:
  CI:
    runs-on: windows-2019
    steps:
    - name: Print Windows info
      run: powershell -c "gp 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion'"
    - name: Print environment variables
      run: set
    - name: Print path
      run: powershell -c "$Env:Path -split ';' | Where-Object { Test-Path $_ }"
