name: ci
on: push
defaults:
  run:
    shell: cmd
jobs:
  ci:
    runs-on: windows-2019
    steps:
    - name: curl
      run: curl -O https://raw.githubusercontent.com/MarkTiedemann/win-ci-playground/master/ci.cmd
    - name: ci
      run: ci.cmd
