name: ci
on: push
defaults:
  run:
    shell: cmd
    working-directory: .
jobs:
  ci:
    runs-on: windows-2019
    steps:
    - name: git clone https://github.com/MarkTiedemann/win-ci-playground
      run: git clone https://github.com/MarkTiedemann/win-ci-playground
    - name: ci.cmd
      run: ci.cmd
