name: ci
on: push
defaults:
  run:
    shell: cmd
jobs:
  ci:
    runs-on: windows-2019
    steps:
    - name: Init
      run: |
        set
        powershell -c "gp 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion'"
