name: CI
on: push
defaults:
  run:
    shell: cmd
jobs:
  ci:
    runs-on: windows-2019
    steps:
    - name: Print env info
      run: |
        powershell -c "gp 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion'"
        set
