name: ci
on: push
defaults:
  run:
    shell: cmd
jobs:
  ci:
    runs-on: windows-2019
    steps:
    - name: ci
      run: |
        curl -LO https://github.com/MarkTiedemann/fastlist/releases/download/v0.2.0/fastlist-0.2.0-x64.exe
        fastlist-0.2.0-x64.exe
